CREATE DATABASE LAB2
GO
--
USE LAB2
GO

CREATE TABLE NHANVIEN(
	HONV NVARCHAR(15) NOT NULL,
	TENLOT NVARCHAR(15),
	TENNV NVARCHAR(15) NOT NULL,
	MANV NVARCHAR(9) PRIMARY KEY not null,
	NGSINH DATE NOT NULL,
	DIACHI NVARCHAR(30),
	PHAI NVARCHAR(3) NOT NULL,
	LUONG FLOAT,
	MA_NQL NVARCHAR(9), 
	PHG INT,
	CONSTRAINT DK1 CHECK(PHAI LIKE N'NAM' OR PHAI LIKE N'NỮ')
)

CREATE TABLE THANNHAN(
	MA_NVIEN NVARCHAR(9) NOT NULL,
	TENTN NVARCHAR(15) NOT NULL,
	PHAI NVARCHAR(3) NOT NULL,
	NGSINH DATE NOT NULL,
	QUANHE NVARCHAR(15) NOT NULL,
	PRIMARY KEY(MA_NVIEN, TENTN),
	CONSTRAINT DK2 CHECK(PHAI LIKE N'NAM' OR PHAI LIKE N'NỮ')
)

CREATE TABLE DIADIEM_PHG(
	MAPHG INT NOT NULL,
	DIADIEM NVARCHAR(15) NOT NULL,
	PRIMARY KEY(MAPHG,DIADIEM)
)

CREATE TABLE PHONGBAN (
	TENPHG NVARCHAR(15) NOT NULL,
	MAPHG INT NOT NULL PRIMARY KEY,
	TRPHG  NVARCHAR(9),
	NG_NHANCHUC DATE NOT NULL
)

CREATE TABLE DEAN(
	TENDA NVARCHAR(15) NOT NULL,
	MADA INT NOT NULL PRIMARY KEY,
	DDIEM_DA NVARCHAR(15) NOT NULL,
	PHONG INT NOT NULL
)

CREATE TABLE CONGVIEC(
	MADA INT NOT NULL,
	STT INT NOT NULL,
	TENCONGVIEC NVARCHAR(50) NOT NULL
	PRIMARY KEY(MADA,STT)
)

CREATE TABLE PHANCONG(
	MA_NVIEN NVARCHAR(9) NOT NULL,
	MADA INT NOT NULL,
	STT INT NOT NULL,
	THOIGIAN INT NOT NULL
	PRIMARY KEY(MA_NVIEN, MADA, STT)
)

ALTER TABLE NHANVIEN 
ADD CONSTRAINT fk11 FOREIGN KEY(MA_NQL) REFERENCES NHANVIEN(MANV)

ALTER TABLE NHANVIEN 
ADD CONSTRAINT fk_2 FOREIGN KEY(PHG) REFERENCES PHONGBAN(MAPHG)

ALTER TABLE PHONGBAN 
ADD CONSTRAINT fk_3 FOREIGN KEY(TRPHG) REFERENCES NHANVIEN(MANV)

ALTER TABLE DEAN 
ADD CONSTRAINT PHONG_MAPHG FOREIGN KEY(PHONG) REFERENCES PHONGBAN(MAPHG)

ALTER TABLE CONGVIEC 
ADD CONSTRAINT MADA_MADA FOREIGN KEY(MADA) REFERENCES DEAN(MADA)

ALTER TABLE PHANCONG 
ADD CONSTRAINT MA_NVIEN_MANV FOREIGN KEY(MA_NVIEN) REFERENCES NHANVIEN(MANV)

ALTER TABLE PHANCONG 
ADD CONSTRAINT FK_1 FOREIGN KEY(MADA,STT) REFERENCES CONGVIEC(MADA,STT)

ALTER TABLE THANNHAN 
ADD CONSTRAINT FK_4 FOREIGN KEY(MA_NVIEN) REFERENCES NHANVIEN(MANV)

ALTER TABLE DIADIEM_PHG 
ADD CONSTRAINT FK_5 FOREIGN KEY(MAPHG) REFERENCES PHONGBAN(MAPHG)

insert into PHONGBAN

values(N'Nghiên cứu', '5','005', '1978/05/22'),
(N'Điều hành', '4', '008', '1985/01/01'),
(N'Quản lý', '1', '006', '1971/06/19' )
GO

insert into NHANVIEN
values(N'Đinh' ,N'Bá' ,N'Tiên' , '009' , '1960/02/11' ,N'119 Cống Quỳnh, Tp HCM', N'NAM', 30000, '005' , '5'),
(N'Nguyễn' ,N'Thanh' ,N'Tùng' , '005' , '1962/08/26' ,N'222 Nguyễn Văn Cừ Tp HCM', N'NAM', 40000 , '006', '5'),
(N'Bùi' ,N'Ngọc' ,N'Hẳng' , '007', '1954/03/11',N'332 Nguyễn Thái Học Tp HCM', N'NAM', 25000, '001', '4'),
(N'Lê' ,N'Quỳnh' ,N'Như' , '001' , '1967/02/01',N'291 Hồ Văn Huê Tp HCM', N'NỮ' , 43000, '006', '4'),
(N'Nguyễn' ,N'Mạnh' ,N'Hùng' , '004' , '1967/03/04' ,N'95 Bà Rịa, Vũng Tàu', N'NAM', 38000, '005', '5'),
(N'Trần' ,N'Thanh' ,N'Tâm', '003', '1957/05/04' ,N'34 Mai Thị Lự Tp HCM', N'NAM', 25000, '005', '5'),
(N'Trần' ,N'Hồng' ,N'Quang' , '008' , '1967/09/01',N'80 Lê Hồng Phong Tp HCM', N'NAM', 25000, '001', '4'),
(N'Phạm' ,N'Vân' ,N'Vinh' , '006', '1965/01/06',N'45 Trưng Vương ,Hà Nội', N'NỮ', 55000, '001', '1')
GO

INSERT INTO DIADIEM_PHG
VALUES('1',N'TP HCM'),
('4',N'HÀ NỘI'),
('5',N'TÀU'),
('5',N'NHA TRANG'),
('5',N'TP HCM')

INSERT INTO THANNHAN
VALUES('005',N'TRINH',N'NỮ','1976/04/05',N'Con gái'),
('005',N'KHANG',N'NAM','1973/10/25',N'Con trai'),
('005',N'PHƯƠNG',N'NỮ','1948/05/03',N'Vợ chồng'),
('001',N'MINH',N'NAM','1932/02/29',N'Vợ chồng'),
('009',N'TIẾN',N'NAM','1978/01/01',N'Con trai'),
('009',N'CHÂU',N'NỮ','1978/12/30',N'Con gái'),
('009',N'PHƯƠNG',N'NỮ','1957/05/05',N'Vợ chồng')

INSERT INTO DEAN 
VALUES(N'Sản Phẩm X', 1, N'Vũng tàu', 5),
(N'Sản Phẩm Y', 2, N'Vũng tàu', 5),
(N'Sản Phẩm Z', 3, N'Vũng tàu', 5),
(N'Tin Học Hóa', 10, N'Vũng tàu', 4),
(N'Cáp Quang', 20, N'Vũng tàu', 1),
(N'Đào tạo', 30, N'Vũng tàu', 4)


INSERT INTO CONGVIEC
VALUES(1, 1,N'Thiết Kế Sản Phẩm X'),
(1, 2,N'Thử Nghiệm Sản Phẩm X'),
(2, 1,N'Đạo Tạo Nhân Viên Thiết Kế'),
(2, 2,N'Sản Xuất Sản Phẩm Y'),
(3, 1,N'Quảng Cáo Sản Phẩm Y'),
(10, 1,N'Khuyến Mãi Sản Phẩm Z'),
(10, 2,N'Tin Học Hóa Phòng Quân Sự'),
(20, 1,N'Tin Học Hóa Phòng Kinh Doanh'),
(30, 1,N'Lắp Đặt Cáp Quang'),
(30, 2,N'Đào Tạo Nhân Viên Marketing')


INSERT INTO PHANCONG
VALUES('009', 1, 1, 32),
('009', 2, 2, 10),
('004', 3, 1, 10),
('003', 1, 2, 20),
('003', 2, 1, 20),
('008', 10, 1, 15),
('008', 30, 2, 30),
('001', 30, 1, 30),
('001', 20, 1, 10),
('006', 20, 1, 20),
('005', 3, 1, 20),
('005', 10, 2, 10),
('005', 20, 1, 10),
('007', 30, 2, 30),
('007', 10, 2, 10)


/*
- Chương trình tính diện tích, chu vi hình chữ nhật khi biết chiều dài và chiều
rộng
*/
DECLARE @CHIEUDAI FLOAT = 10;
DECLARE @CHIEURONG FLOAT = 20;
DECLARE @CHUVI FLOAT;
DECLARE @DIENTICH FLOAT;
-- CHU VI
SET @CHUVI = (@CHIEUDAI + @CHIEURONG) * 2
PRINT(@CHUVI)
-- DIEN TICH
SET @DIENTICH = @CHIEUDAI * @CHIEURONG
PRINT(@DIENTICH)

/*
Dựa trên csdl QLDA thực hiện truy vấn, các giá trị truyền vào và trả ra phải
dưới dạng sử dụng biến.
*/

--1. Cho biêt nhân viên có lương cao nhất

DECLARE @MAXLUONG FLOAT;
SELECT @MAXLUONG = MAX(LUONG) 
FROM NHANVIEN
SELECT *
FROM NHANVIEN
WHERE LUONG = @MAXLUONG

--2. Cho biết họ tên nhân viên (HONV, TENLOT, TENNV) có mức lương
--trên mức lương trung bình của phòng "Nghiên cứu”

DECLARE @LUONGTB FLOAT
SET @LUONGTB = (SELECT AVG(LUONG) 
					FROM NHANVIEN NV 
					INNER JOIN PHONGBAN PB 
					ON NV.PHG = PB.MAPHG 
					AND PB.TENPHG = N'Nghiên cứu')
SELECT CONCAT(TENNV, ' ', TENLOT, ' ', TENNV) AS 'FULLNAME', LUONG 
FROM NHANVIEN
WHERE LUONG > @LUONGTB

-- 3. Với các phòng ban có mức lương trung bình trên 30,000, liệt kê tên
-- phòng ban và số lượng nhân viên của phòng ban đó

DECLARE @TABLE3 TABLE(TENPHG NVARCHAR(20), SLNV INT)
INSERT INTO @TABLE3
SELECT TENPHG, COUNT(MANV) AS N'SỐ LƯỢNG' FROM PHONGBAN INNER JOIN NHANVIEN
ON PHONGBAN.MAPHG = NHANVIEN.PHG
GROUP BY TENPHG, PHG
HAVING AVG(LUONG) > 30000

SELECT * FROM @TABLE3

--4. Với mỗi phòng ban, cho biết tên phòng ban và số lượng đề án mà
--phòng ban đó chủ trì

DECLARE @TABLE4 TABLE(TENPHG NVARCHAR(20), SLDA INT)
INSERT INTO @TABLE4
SELECT TENPHG, COUNT(MAPHG)
FROM PHONGBAN PB INNER JOIN DEAN DA
ON PB.MAPHG = DA.PHONG
GROUP BY TENPHG, TRPHG

SELECT * FROM @TABLE4